import "dotenv/config.js";

const env = {
NODE_ENV: process.env.NODE_ENV || "development",
PORT: process.env.PORT || 7000,
MONGO_URI: process.env.MONGO_URI ,
CLIENT_URL: process.env.CLIENT_URL,
ACCESS_TOKEN_SECRET: process.env.ACCESS_TOKEN_SECRET ,
ACCESS_TOKEN_EXPIRES_IN: process.env.ACCESS_TOKEN_EXPIRES_IN || "1h",
REFRESH_TOKEN_SECRET: process.env.REFRESH_TOKEN_SECRET ,
REFRESH_TOKEN_EXPIRES_IN: process.env.REFRESH_TOKEN_EXPIRES_IN || "7d",
ADMIN_NAME: process.env.ADMIN_NAME ,
ADMIN_EMAIL: process.env.ADMIN_EMAIL  ,
ADMIN_PASSWORD: process.env.ADMIN_PASSWORD ,
SOCKET_URL: process.env.SOCKET_URL ,
SOCKET_CORS_ORIGIN: process.env.SOCKET_CORS_ORIGIN ,
EMAIL_USER: process.env.EMAIL_USER,
EMAIL_PASSWORD: process.env.EMAIL_PASSWORD,
CLOUDINARY_CLOUD_NAME: process.env.CLOUDINARY_CLOUD_NAME,
CLOUDINARY_API_KEY: process.env.CLOUDINARY_API_KEY,
CLOUDINARY_API_SECRET: process.env.CLOUDINARY_API_SECRET,
}

export default env;